services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: pls_al_llamado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pls_al_llamado_data:/var/lib/postgresql/data

volumes:
  pls_al_llamado_data:
