/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'aid-intakes': AidIntake;
    resources: Resource;
    needs: Need;
    distributions: Distribution;
    'distribution-evidence': DistributionEvidence;
    announcements: Announcement;
    'community-notices': CommunityNotice;
    services: Service;
    bulletins: Bulletin;
    'volunteer-activities': VolunteerActivity;
    'support-requests': SupportRequest;
    media: Media;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'aid-intakes': AidIntakesSelect<false> | AidIntakesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    needs: NeedsSelect<false> | NeedsSelect<true>;
    distributions: DistributionsSelect<false> | DistributionsSelect<true>;
    'distribution-evidence': DistributionEvidenceSelect<false> | DistributionEvidenceSelect<true>;
    announcements: AnnouncementsSelect<false> | AnnouncementsSelect<true>;
    'community-notices': CommunityNoticesSelect<false> | CommunityNoticesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    bulletins: BulletinsSelect<false> | BulletinsSelect<true>;
    'volunteer-activities': VolunteerActivitiesSelect<false> | VolunteerActivitiesSelect<true>;
    'support-requests': SupportRequestsSelect<false> | SupportRequestsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * El primer usuario registrado en Payload debe conservar el rol Administrador.
   */
  role:
    | 'admin'
    | 'super-admin'
    | 'que-tenemos'
    | 'que-necesitamos'
    | 'anuncios'
    | 'boletin'
    | 'servicios'
    | 'inventario'
    | 'distribucion'
    | 'comunicados'
    | 'administracion';
  phone?: string | null;
  active?: boolean | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Registro de ayudas recibidas antes de clasificarlas o incorporarlas al inventario.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aid-intakes".
 */
export interface AidIntake {
  id: string;
  resourceName: string;
  category:
    | 'alimentos'
    | 'agua'
    | 'aseo'
    | 'salud'
    | 'abrigo'
    | 'bebes'
    | 'herramientas'
    | 'mascotas'
    | 'cocina'
    | 'higiene'
    | 'transporte'
    | 'alojamiento'
    | 'energia'
    | 'construccion'
    | 'otros';
  quantity: number;
  /**
   * Ej.: cajas, kits, litros o unidades. Indica qué representa la cantidad.
   */
  unit: string;
  sourceType: 'donacion' | 'alianza' | 'compra' | 'prestamo' | 'otro';
  /**
   * Nombre de la organización o referencia interna. No publicar datos personales.
   */
  sourceReference?: string | null;
  receivedAt: string;
  status: 'recibida' | 'en-clasificacion' | 'incorporada' | 'no-apta';
  publicVisible?: boolean | null;
  /**
   * Lo fija como una de las ayudas prioritarias en la vista pública.
   */
  featured?: boolean | null;
  notes?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inventario visible y operativo del centro de acopio PLs al llamado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: string;
  name: string;
  category:
    | 'alimentos'
    | 'agua'
    | 'aseo'
    | 'salud'
    | 'abrigo'
    | 'bebes'
    | 'herramientas'
    | 'mascotas'
    | 'cocina'
    | 'higiene'
    | 'transporte'
    | 'alojamiento'
    | 'energia'
    | 'construccion'
    | 'otros';
  quantity: number;
  /**
   * Indica qué representa la cantidad disponible.
   */
  unit: string;
  status: 'disponible' | 'limitado' | 'agotado';
  publicVisible?: boolean | null;
  /**
   * Lo fija como un recurso prioritario en la vista pública.
   */
  featured?: boolean | null;
  notes?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs".
 */
export interface Need {
  id: string;
  title: string;
  detail: string;
  category:
    | 'alimentos'
    | 'agua'
    | 'aseo'
    | 'salud'
    | 'abrigo'
    | 'bebes'
    | 'herramientas'
    | 'mascotas'
    | 'cocina'
    | 'higiene'
    | 'transporte'
    | 'alojamiento'
    | 'energia'
    | 'construccion'
    | 'otros';
  quantity?: number | null;
  /**
   * Indica qué representa la cantidad solicitada.
   */
  unit?: string | null;
  priority: 'critica' | 'alta' | 'media';
  status: 'abierta' | 'en-gestion' | 'cubierta' | 'cerrada';
  zone?: string | null;
  publicVisible?: boolean | null;
  /**
   * Lo fija como una de las necesidades prioritarias en la vista pública.
   */
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributions".
 */
export interface Distribution {
  id: string;
  resourceName: string;
  quantity: number;
  /**
   * Indica qué representa la cantidad distribuida.
   */
  unit: string;
  date: string;
  destination: string;
  organization: string;
  status: 'pendiente' | 'en-ruta' | 'entregado';
  publicVisible?: boolean | null;
  notes?: string | null;
  /**
   * Campo legado. Las nuevas evidencias se registran en la colección separada de evidencias de distribución.
   */
  evidence?:
    | {
        image: string | Media;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  r2Key?: string | null;
  r2Filename?: string | null;
  r2MimeType?: string | null;
  r2Filesize?: number | null;
  uploadedByUserId?: string | null;
  uploadedByName?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Registro visual separado para documentar salidas de distribución sin datos sensibles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distribution-evidence".
 */
export interface DistributionEvidence {
  id: string;
  sourceType: 'distribucion' | 'otro';
  distribution?: (string | null) | Distribution;
  otherReference?: string | null;
  image?: (string | null) | Media;
  publicImagePath?: string | null;
  title: string;
  description: string;
  status: 'borrador' | 'publicado' | 'archivado';
  publicVisible?: boolean | null;
  publishedAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements".
 */
export interface Announcement {
  id: string;
  title: string;
  body: string;
  type: 'horario' | 'necesidad' | 'distribucion' | 'voluntariado' | 'oficial' | 'impacto';
  status: 'borrador' | 'publicado' | 'archivado';
  featured?: boolean | null;
  publicVisible?: boolean | null;
  publishedAt?: string | null;
  expiresAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Comunicados comunitarios moderados: mascotas, vivienda, objetos e información de interés general.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-notices".
 */
export interface CommunityNotice {
  id: string;
  title: string;
  body: string;
  category:
    | 'mascota-perdida'
    | 'mascota-encontrada'
    | 'apoyo-comunitario'
    | 'objeto-perdido'
    | 'informacion-comunitaria'
    | 'vivienda'
    | 'otro';
  image?: (string | null) | Media;
  publicImagePath?: string | null;
  location: string;
  contact: string;
  status: 'borrador' | 'publicado' | 'archivado';
  featured?: boolean | null;
  publicVisible?: boolean | null;
  publishedAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Servicios gratuitos, ofrecidos por la comunidad o que todavía se necesitan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  description: string;
  type: 'gratuito' | 'ofrecido' | 'necesitado';
  category: string;
  provider: string;
  location: string;
  price?: string | null;
  status: 'borrador' | 'publicado' | 'archivado';
  publicVisible?: boolean | null;
  publishedAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Boletines largos con avances, registros y aprendizajes de la operación.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulletins".
 */
export interface Bulletin {
  id: string;
  title: string;
  summary: string;
  body: string;
  category: string;
  author: string;
  status: 'borrador' | 'publicado' | 'archivado';
  featured?: boolean | null;
  publicVisible?: boolean | null;
  publishedAt?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-activities".
 */
export interface VolunteerActivity {
  id: string;
  title: string;
  description: string;
  date: string;
  startTime: string;
  endTime: string;
  location: string;
  capacity: number;
  registered?: number | null;
  status: 'abierta' | 'llena' | 'finalizada';
  publicVisible?: boolean | null;
  lead?: string | null;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solicitudes recibidas desde la página pública. No se publican nombres ni datos individuales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-requests".
 */
export interface SupportRequest {
  id: string;
  helpType: 'necesitar-ayuda' | 'ofrecer-ayuda';
  requestType: 'recursos' | 'oferta' | 'transporte' | 'voluntariado';
  source: 'public-form' | 'need-offer';
  category: string;
  zone: string;
  /**
   * Opcional. Usa solo números enteros positivos.
   */
  quantity?: number | null;
  /**
   * Se necesita cuando indicas una cantidad.
   */
  quantityUnit?:
    | (
        | 'unidades'
        | 'cajas'
        | 'kits'
        | 'paquetes'
        | 'bultos'
        | 'pares'
        | 'pacas'
        | 'canecas'
        | 'litros'
        | 'turnos'
        | 'horas'
        | 'recorridos'
        | 'cupos'
        | 'jornadas'
      )
    | null;
  description: string;
  contactName: string;
  /**
   * Número para coordinar la ayuda. No se publica.
   */
  phone: string;
  status: 'pendiente' | 'en-revision' | 'asignada' | 'atendida' | 'cerrada';
  internalNotes?: string | null;
  privacyAccepted: boolean;
  /**
   * Se completa automáticamente con la persona que creó el registro.
   */
  registeredBy?: string | null;
  registeredByUserId?: string | null;
  /**
   * Se actualiza automáticamente con la última persona que lo modificó.
   */
  updatedBy?: string | null;
  updatedByUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trazabilidad inmutable de accesos y cambios realizados por usuarios autenticados. No almacena contraseñas, tokens ni contenidos completos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  occurredAt: string;
  action: 'login' | 'logout' | 'create' | 'update' | 'delete' | 'error';
  source: 'payload-admin' | 'equipo' | 'sistema';
  actorName: string;
  actorEmail?: string | null;
  actorRole?: string | null;
  actorId?: string | null;
  entityType: 'collection' | 'global' | 'auth' | 'system';
  entitySlug: string;
  documentId?: string | null;
  documentLabel?: string | null;
  changedFields?: string | null;
  summary: string;
  path?: string | null;
  method?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  success: boolean;
  statusCode?: number | null;
  errorName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'aid-intakes';
        value: string | AidIntake;
      } | null)
    | ({
        relationTo: 'resources';
        value: string | Resource;
      } | null)
    | ({
        relationTo: 'needs';
        value: string | Need;
      } | null)
    | ({
        relationTo: 'distributions';
        value: string | Distribution;
      } | null)
    | ({
        relationTo: 'distribution-evidence';
        value: string | DistributionEvidence;
      } | null)
    | ({
        relationTo: 'announcements';
        value: string | Announcement;
      } | null)
    | ({
        relationTo: 'community-notices';
        value: string | CommunityNotice;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'bulletins';
        value: string | Bulletin;
      } | null)
    | ({
        relationTo: 'volunteer-activities';
        value: string | VolunteerActivity;
      } | null)
    | ({
        relationTo: 'support-requests';
        value: string | SupportRequest;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  active?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aid-intakes_select".
 */
export interface AidIntakesSelect<T extends boolean = true> {
  resourceName?: T;
  category?: T;
  quantity?: T;
  unit?: T;
  sourceType?: T;
  sourceReference?: T;
  receivedAt?: T;
  status?: T;
  publicVisible?: T;
  featured?: T;
  notes?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  quantity?: T;
  unit?: T;
  status?: T;
  publicVisible?: T;
  featured?: T;
  notes?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "needs_select".
 */
export interface NeedsSelect<T extends boolean = true> {
  title?: T;
  detail?: T;
  category?: T;
  quantity?: T;
  unit?: T;
  priority?: T;
  status?: T;
  zone?: T;
  publicVisible?: T;
  featured?: T;
  publishedAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distributions_select".
 */
export interface DistributionsSelect<T extends boolean = true> {
  resourceName?: T;
  quantity?: T;
  unit?: T;
  date?: T;
  destination?: T;
  organization?: T;
  status?: T;
  publicVisible?: T;
  notes?: T;
  evidence?:
    | T
    | {
        image?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "distribution-evidence_select".
 */
export interface DistributionEvidenceSelect<T extends boolean = true> {
  sourceType?: T;
  distribution?: T;
  otherReference?: T;
  image?: T;
  publicImagePath?: T;
  title?: T;
  description?: T;
  status?: T;
  publicVisible?: T;
  publishedAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcements_select".
 */
export interface AnnouncementsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  type?: T;
  status?: T;
  featured?: T;
  publicVisible?: T;
  publishedAt?: T;
  expiresAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "community-notices_select".
 */
export interface CommunityNoticesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  category?: T;
  image?: T;
  publicImagePath?: T;
  location?: T;
  contact?: T;
  status?: T;
  featured?: T;
  publicVisible?: T;
  publishedAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  category?: T;
  provider?: T;
  location?: T;
  price?: T;
  status?: T;
  publicVisible?: T;
  publishedAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulletins_select".
 */
export interface BulletinsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  category?: T;
  author?: T;
  status?: T;
  featured?: T;
  publicVisible?: T;
  publishedAt?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-activities_select".
 */
export interface VolunteerActivitiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  capacity?: T;
  registered?: T;
  status?: T;
  publicVisible?: T;
  lead?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-requests_select".
 */
export interface SupportRequestsSelect<T extends boolean = true> {
  helpType?: T;
  requestType?: T;
  source?: T;
  category?: T;
  zone?: T;
  quantity?: T;
  quantityUnit?: T;
  description?: T;
  contactName?: T;
  phone?: T;
  status?: T;
  internalNotes?: T;
  privacyAccepted?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  r2Key?: T;
  r2Filename?: T;
  r2MimeType?: T;
  r2Filesize?: T;
  uploadedByUserId?: T;
  uploadedByName?: T;
  registeredBy?: T;
  registeredByUserId?: T;
  updatedBy?: T;
  updatedByUserId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  occurredAt?: T;
  action?: T;
  source?: T;
  actorName?: T;
  actorEmail?: T;
  actorRole?: T;
  actorId?: T;
  entityType?: T;
  entitySlug?: T;
  documentId?: T;
  documentLabel?: T;
  changedFields?: T;
  summary?: T;
  path?: T;
  method?: T;
  ipAddress?: T;
  userAgent?: T;
  success?: T;
  statusCode?: T;
  errorName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  centerName: string;
  address: string;
  hours: string;
  centerStatus: 'abierto' | 'limitado' | 'cerrado';
  donationInstructions: string;
  heroMessage: string;
  phone: string;
  lastOperationalUpdate?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  centerName?: T;
  address?: T;
  hours?: T;
  centerStatus?: T;
  donationInstructions?: T;
  heroMessage?: T;
  phone?: T;
  lastOperationalUpdate?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
