// Catálogo DIVIPOLA consultado desde el geoportal del DANE. Se mantiene local
// para que los formularios funcionen igual en web, móvil y tablet sin depender
// de una API externa en cada selección.
export type ColombiaDepartment = { code: string; name: string; municipalities: string[] }

export const colombiaDepartments: ColombiaDepartment[] = [
  {
    "code": "91",
    "name": "Amazonas",
    "municipalities": [
      "EL ENCANTO",
      "LA CHORRERA",
      "LA PEDRERA",
      "LA VICTORIA",
      "LETICIA",
      "MIRITÍ - PARANÁ",
      "PUERTO ALEGRÍA",
      "PUERTO ARICA",
      "PUERTO NARIÑO",
      "PUERTO SANTANDER",
      "TARAPACÁ"
    ]
  },
  {
    "code": "05",
    "name": "Antioquia",
    "municipalities": [
      "ABEJORRAL",
      "ABRIAQUÍ",
      "ALEJANDRÍA",
      "AMAGÁ",
      "AMALFI",
      "ANDES",
      "ANGELÓPOLIS",
      "ANGOSTURA",
      "ANORÍ",
      "ANZÁ",
      "APARTADÓ",
      "ARBOLETES",
      "ARGELIA",
      "ARMENIA",
      "BARBOSA",
      "BELLO",
      "BELMIRA",
      "BETANIA",
      "BETULIA",
      "BRICEÑO",
      "BURITICÁ",
      "CÁCERES",
      "CAICEDO",
      "CALDAS",
      "CAMPAMENTO",
      "CAÑASGORDAS",
      "CARACOLÍ",
      "CARAMANTA",
      "CAREPA",
      "CAROLINA",
      "CAUCASIA",
      "CHIGORODÓ",
      "CISNEROS",
      "CIUDAD BOLÍVAR",
      "COCORNÁ",
      "CONCEPCIÓN",
      "CONCORDIA",
      "COPACABANA",
      "DABEIBA",
      "DONMATÍAS",
      "EBÉJICO",
      "EL BAGRE",
      "EL CARMEN DE VIBORAL",
      "EL SANTUARIO",
      "ENTRERRÍOS",
      "ENVIGADO",
      "FREDONIA",
      "FRONTINO",
      "GIRALDO",
      "GIRARDOTA",
      "GÓMEZ PLATA",
      "GRANADA",
      "GUADALUPE",
      "GUARNE",
      "GUATAPÉ",
      "HELICONIA",
      "HISPANIA",
      "ITAGÜÍ",
      "ITUANGO",
      "JARDÍN",
      "JERICÓ",
      "LA CEJA",
      "LA ESTRELLA",
      "LA PINTADA",
      "LA UNIÓN",
      "LIBORINA",
      "MACEO",
      "MARINILLA",
      "MEDELLÍN",
      "MONTEBELLO",
      "MURINDÓ",
      "MUTATÁ",
      "NARIÑO",
      "NECHÍ",
      "NECOCLÍ",
      "OLAYA",
      "PEÑOL",
      "PEQUE",
      "PUEBLORRICO",
      "PUERTO BERRÍO",
      "PUERTO NARE",
      "PUERTO TRIUNFO",
      "REMEDIOS",
      "RETIRO",
      "RIONEGRO",
      "SABANALARGA",
      "SABANETA",
      "SALGAR",
      "SAN ANDRÉS DE CUERQUÍA",
      "SAN CARLOS",
      "SAN FRANCISCO",
      "SAN JERÓNIMO",
      "SAN JOSÉ DE LA MONTAÑA",
      "SAN JUAN DE URABÁ",
      "SAN LUIS",
      "SAN PEDRO DE LOS MILAGROS",
      "SAN PEDRO DE URABÁ",
      "SAN RAFAEL",
      "SAN ROQUE",
      "SAN VICENTE FERRER",
      "SANTA BÁRBARA",
      "SANTA FÉ DE ANTIOQUIA",
      "SANTA ROSA DE OSOS",
      "SANTO DOMINGO",
      "SEGOVIA",
      "SONSÓN",
      "SOPETRÁN",
      "TÁMESIS",
      "TARAZÁ",
      "TARSO",
      "TITIRIBÍ",
      "TOLEDO",
      "TURBO",
      "URAMITA",
      "URRAO",
      "VALDIVIA",
      "VALPARAÍSO",
      "VEGACHÍ",
      "VENECIA",
      "VIGÍA DEL FUERTE",
      "YALÍ",
      "YARUMAL",
      "YOLOMBÓ",
      "YONDÓ",
      "ZARAGOZA"
    ]
  },
  {
    "code": "81",
    "name": "Arauca",
    "municipalities": [
      "ARAUCA",
      "ARAUQUITA",
      "CRAVO NORTE",
      "FORTUL",
      "PUERTO RONDÓN",
      "SARAVENA",
      "TAME"
    ]
  },
  {
    "code": "88",
    "name": "Archipiélago de San Andrés, Providencia y Santa Catalina",
    "municipalities": [
      "PROVIDENCIA",
      "SAN ANDRÉS"
    ]
  },
  {
    "code": "08",
    "name": "Atlántico",
    "municipalities": [
      "BARANOA",
      "BARRANQUILLA",
      "CAMPO DE LA CRUZ",
      "CANDELARIA",
      "GALAPA",
      "JUAN DE ACOSTA",
      "LURUACO",
      "MALAMBO",
      "MANATÍ",
      "PALMAR DE VARELA",
      "PIOJÓ",
      "POLONUEVO",
      "PONEDERA",
      "PUERTO COLOMBIA",
      "REPELÓN",
      "SABANAGRANDE",
      "SABANALARGA",
      "SANTA LUCÍA",
      "SANTO TOMÁS",
      "SOLEDAD",
      "SUAN",
      "TUBARÁ",
      "USIACURÍ"
    ]
  },
  {
    "code": "11",
    "name": "Bogotá D.C.",
    "municipalities": [
      "BOGOTÁ"
    ]
  },
  {
    "code": "13",
    "name": "Bolívar",
    "municipalities": [
      "ACHÍ",
      "ALTOS DEL ROSARIO",
      "ARENAL",
      "ARJONA",
      "ARROYOHONDO",
      "BARRANCO DE LOBA",
      "CALAMAR",
      "CANTAGALLO",
      "CARTAGENA DE INDIAS",
      "CICUCO",
      "CLEMENCIA",
      "CÓRDOBA",
      "EL CARMEN DE BOLÍVAR",
      "EL GUAMO",
      "EL PEÑÓN",
      "HATILLO DE LOBA",
      "MAGANGUÉ",
      "MAHATES",
      "MARGARITA",
      "MARÍA LA BAJA",
      "MOMPÓS",
      "MONTECRISTO",
      "MORALES",
      "NOROSÍ",
      "PINILLOS",
      "REGIDOR",
      "RÍO VIEJO",
      "SAN CRISTÓBAL",
      "SAN ESTANISLAO",
      "SAN FERNANDO",
      "SAN JACINTO",
      "SAN JACINTO DEL CAUCA",
      "SAN JUAN NEPOMUCENO",
      "SAN MARTÍN DE LOBA",
      "SAN PABLO",
      "SANTA CATALINA",
      "SANTA ROSA",
      "SANTA ROSA DEL SUR",
      "SIMITÍ",
      "SOPLAVIENTO",
      "TALAIGUA NUEVO",
      "TIQUISIO",
      "TURBACO",
      "TURBANÁ",
      "VILLANUEVA",
      "ZAMBRANO"
    ]
  },
  {
    "code": "15",
    "name": "Boyacá",
    "municipalities": [
      "ALMEIDA",
      "AQUITANIA",
      "ARCABUCO",
      "BELÉN",
      "BERBEO",
      "BETÉITIVA",
      "BOAVITA",
      "BOYACÁ",
      "BRICEÑO",
      "BUENAVISTA",
      "BUSBANZÁ",
      "CALDAS",
      "CAMPOHERMOSO",
      "CERINZA",
      "CHINAVITA",
      "CHIQUINQUIRÁ",
      "CHÍQUIZA",
      "CHISCAS",
      "CHITA",
      "CHITARAQUE",
      "CHIVATÁ",
      "CHIVOR",
      "CIÉNEGA",
      "CÓMBITA",
      "COPER",
      "CORRALES",
      "COVARACHÍA",
      "CUBARÁ",
      "CUCAITA",
      "CUÍTIVA",
      "DUITAMA",
      "EL COCUY",
      "EL ESPINO",
      "FIRAVITOBA",
      "FLORESTA",
      "GACHANTIVÁ",
      "GÁMEZA",
      "GARAGOA",
      "GUACAMAYAS",
      "GUATEQUE",
      "GUAYATÁ",
      "GÜICÁN DE LA SIERRA",
      "IZA",
      "JENESANO",
      "JERICÓ",
      "LA CAPILLA",
      "LA UVITA",
      "LA VICTORIA",
      "LABRANZAGRANDE",
      "MACANAL",
      "MARIPÍ",
      "MIRAFLORES",
      "MONGUA",
      "MONGUÍ",
      "MONIQUIRÁ",
      "MOTAVITA",
      "MUZO",
      "NOBSA",
      "NUEVO COLÓN",
      "OICATÁ",
      "OTANCHE",
      "PACHAVITA",
      "PÁEZ",
      "PAIPA",
      "PAJARITO",
      "PANQUEBA",
      "PAUNA",
      "PAYA",
      "PAZ DE RÍO",
      "PESCA",
      "PISBA",
      "PUERTO BOYACÁ",
      "QUÍPAMA",
      "RAMIRIQUÍ",
      "RÁQUIRA",
      "RONDÓN",
      "SABOYÁ",
      "SÁCHICA",
      "SAMACÁ",
      "SAN EDUARDO",
      "SAN JOSÉ DE PARE",
      "SAN LUIS DE GACENO",
      "SAN MATEO",
      "SAN MIGUEL DE SEMA",
      "SAN PABLO DE BORBUR",
      "SANTA MARÍA",
      "SANTA ROSA DE VITERBO",
      "SANTA SOFÍA",
      "SANTANA",
      "SATIVANORTE",
      "SATIVASUR",
      "SIACHOQUE",
      "SOATÁ",
      "SOCHA",
      "SOCOTÁ",
      "SOGAMOSO",
      "SOMONDOCO",
      "SORA",
      "SORACÁ",
      "SOTAQUIRÁ",
      "SUSACÓN",
      "SUTAMARCHÁN",
      "SUTATENZA",
      "TASCO",
      "TENZA",
      "TIBANÁ",
      "TIBASOSA",
      "TINJACÁ",
      "TIPACOQUE",
      "TOCA",
      "TOGÜÍ",
      "TÓPAGA",
      "TOTA",
      "TUNJA",
      "TUNUNGUÁ",
      "TURMEQUÉ",
      "TUTA",
      "TUTAZÁ",
      "ÚMBITA",
      "VENTAQUEMADA",
      "VILLA DE LEYVA",
      "VIRACACHÁ",
      "ZETAQUIRA"
    ]
  },
  {
    "code": "17",
    "name": "Caldas",
    "municipalities": [
      "AGUADAS",
      "ANSERMA",
      "ARANZAZU",
      "BELALCÁZAR",
      "CHINCHINÁ",
      "FILADELFIA",
      "LA DORADA",
      "LA MERCED",
      "MANIZALES",
      "MANZANARES",
      "MARMATO",
      "MARQUETALIA",
      "MARULANDA",
      "NEIRA",
      "NORCASIA",
      "PÁCORA",
      "PALESTINA",
      "PENSILVANIA",
      "RIOSUCIO",
      "RISARALDA",
      "SALAMINA",
      "SAMANÁ",
      "SAN JOSÉ",
      "SUPÍA",
      "VICTORIA",
      "VILLAMARÍA",
      "VITERBO"
    ]
  },
  {
    "code": "18",
    "name": "Caquetá",
    "municipalities": [
      "ALBANIA",
      "BELÉN DE LOS ANDAQUÍES",
      "CARTAGENA DEL CHAIRÁ",
      "CURILLO",
      "EL DONCELLO",
      "EL PAUJÍL",
      "FLORENCIA",
      "LA MONTAÑITA",
      "MILÁN",
      "MORELIA",
      "PUERTO RICO",
      "SAN JOSÉ DEL FRAGUA",
      "SAN VICENTE DEL CAGUÁN",
      "SOLANO",
      "SOLITA",
      "VALPARAÍSO"
    ]
  },
  {
    "code": "85",
    "name": "Casanare",
    "municipalities": [
      "AGUAZUL",
      "CHÁMEZA",
      "HATO COROZAL",
      "LA SALINA",
      "MANÍ",
      "MONTERREY",
      "NUNCHÍA",
      "OROCUÉ",
      "PAZ DE ARIPORO",
      "PORE",
      "RECETOR",
      "SABANALARGA",
      "SÁCAMA",
      "SAN LUIS DE PALENQUE",
      "TÁMARA",
      "TAURAMENA",
      "TRINIDAD",
      "VILLANUEVA",
      "YOPAL"
    ]
  },
  {
    "code": "19",
    "name": "Cauca",
    "municipalities": [
      "ALMAGUER",
      "ARGELIA",
      "BALBOA",
      "BOLÍVAR",
      "BUENOS AIRES",
      "CAJIBÍO",
      "CALDONO",
      "CALOTO",
      "CORINTO",
      "EL TAMBO",
      "FLORENCIA",
      "GUACHENÉ",
      "GUAPI",
      "INZÁ",
      "JAMBALÓ",
      "LA SIERRA",
      "LA VEGA",
      "LÓPEZ DE MICAY",
      "MERCADERES",
      "MIRANDA",
      "MORALES",
      "PADILLA",
      "PÁEZ",
      "PATÍA",
      "PIAMONTE",
      "PIENDAMÓ - TUNÍA",
      "POPAYÁN",
      "PUERTO TEJADA",
      "PURACÉ",
      "ROSAS",
      "SAN SEBASTIÁN",
      "SANTA ROSA",
      "SANTANDER DE QUILICHAO",
      "SILVIA",
      "SOTARÁ - PAISPAMBA",
      "SUÁREZ",
      "SUCRE",
      "TIMBÍO",
      "TIMBIQUÍ",
      "TORIBÍO",
      "TOTORÓ",
      "VILLA RICA"
    ]
  },
  {
    "code": "20",
    "name": "Cesar",
    "municipalities": [
      "AGUACHICA",
      "AGUSTÍN CODAZZI",
      "ASTREA",
      "BECERRIL",
      "BOSCONIA",
      "CHIMICHAGUA",
      "CHIRIGUANÁ",
      "CURUMANÍ",
      "EL COPEY",
      "EL PASO",
      "GAMARRA",
      "GONZÁLEZ",
      "LA GLORIA",
      "LA JAGUA DE IBIRICO",
      "LA PAZ",
      "MANAURE BALCÓN DEL CESAR",
      "PAILITAS",
      "PELAYA",
      "PUEBLO BELLO",
      "RÍO DE ORO",
      "SAN ALBERTO",
      "SAN DIEGO",
      "SAN MARTÍN",
      "TAMALAMEQUE",
      "VALLEDUPAR"
    ]
  },
  {
    "code": "27",
    "name": "Chocó",
    "municipalities": [
      "ACANDÍ",
      "ALTO BAUDÓ",
      "ATRATO",
      "BAGADÓ",
      "BAHÍA SOLANO",
      "BAJO BAUDÓ",
      "BOJAYÁ",
      "CARMEN DEL DARIÉN",
      "CÉRTEGUI",
      "CONDOTO",
      "EL CANTÓN DEL SAN PABLO",
      "EL CARMEN DE ATRATO",
      "EL LITORAL DEL SAN JUAN",
      "ISTMINA",
      "JURADÓ",
      "LLORÓ",
      "MEDIO ATRATO",
      "MEDIO BAUDÓ",
      "MEDIO SAN JUAN",
      "NÓVITA",
      "NUQUÍ",
      "QUIBDÓ",
      "RÍO IRÓ",
      "RÍO QUITO",
      "RIOSUCIO",
      "SAN JOSÉ DEL PALMAR",
      "SIPÍ",
      "TADÓ",
      "UNGUÍA",
      "UNIÓN PANAMERICANA"
    ]
  },
  {
    "code": "23",
    "name": "Córdoba",
    "municipalities": [
      "AYAPEL",
      "BUENAVISTA",
      "CANALETE",
      "CERETÉ",
      "CHIMÁ",
      "CHINÚ",
      "CIÉNAGA DE ORO",
      "COTORRA",
      "LA APARTADA",
      "LORICA",
      "LOS CÓRDOBAS",
      "MOMIL",
      "MONTELÍBANO",
      "MONTERÍA",
      "MOÑITOS",
      "PLANETA RICA",
      "PUEBLO NUEVO",
      "PUERTO ESCONDIDO",
      "PUERTO LIBERTADOR",
      "PURÍSIMA DE LA CONCEPCIÓN",
      "SAHAGÚN",
      "SAN ANDRÉS DE SOTAVENTO",
      "SAN ANTERO",
      "SAN BERNARDO DEL VIENTO",
      "SAN CARLOS",
      "SAN JOSÉ DE URÉ",
      "SAN PELAYO",
      "TIERRALTA",
      "TUCHÍN",
      "VALENCIA"
    ]
  },
  {
    "code": "25",
    "name": "Cundinamarca",
    "municipalities": [
      "AGUA DE DIOS",
      "ALBÁN",
      "ANAPOIMA",
      "ANOLAIMA",
      "APULO",
      "ARBELÁEZ",
      "BELTRÁN",
      "BITUIMA",
      "BOJACÁ",
      "CABRERA",
      "CACHIPAY",
      "CAJICÁ",
      "CAPARRAPÍ",
      "CÁQUEZA",
      "CARMEN DE CARUPA",
      "CHAGUANÍ",
      "CHÍA",
      "CHIPAQUE",
      "CHOACHÍ",
      "CHOCONTÁ",
      "COGUA",
      "COTA",
      "CUCUNUBÁ",
      "EL COLEGIO",
      "EL PEÑÓN",
      "EL ROSAL",
      "FACATATIVÁ",
      "FÓMEQUE",
      "FOSCA",
      "FUNZA",
      "FÚQUENE",
      "FUSAGASUGÁ",
      "GACHALÁ",
      "GACHANCIPÁ",
      "GACHETÁ",
      "GAMA",
      "GIRARDOT",
      "GRANADA",
      "GUACHETÁ",
      "GUADUAS",
      "GUASCA",
      "GUATAQUÍ",
      "GUATAVITA",
      "GUAYABAL DE SÍQUIMA",
      "GUAYABETAL",
      "GUTIÉRREZ",
      "JERUSALÉN",
      "JUNÍN",
      "LA CALERA",
      "LA MESA",
      "LA PALMA",
      "LA PEÑA",
      "LA VEGA",
      "LENGUAZAQUE",
      "MACHETÁ",
      "MADRID",
      "MANTA",
      "MEDINA",
      "MOSQUERA",
      "NARIÑO",
      "NEMOCÓN",
      "NILO",
      "NIMAIMA",
      "NOCAIMA",
      "PACHO",
      "PAIME",
      "PANDI",
      "PARATEBUENO",
      "PASCA",
      "PUERTO SALGAR",
      "PULÍ",
      "QUEBRADANEGRA",
      "QUETAME",
      "QUIPILE",
      "RICAURTE",
      "SAN ANTONIO DEL TEQUENDAMA",
      "SAN BERNARDO",
      "SAN CAYETANO",
      "SAN FRANCISCO",
      "SAN JUAN DE RIOSECO",
      "SASAIMA",
      "SESQUILÉ",
      "SIBATÉ",
      "SILVANIA",
      "SIMIJACA",
      "SOACHA",
      "SOPÓ",
      "SUBACHOQUE",
      "SUESCA",
      "SUPATÁ",
      "SUSA",
      "SUTATAUSA",
      "TABIO",
      "TAUSA",
      "TENA",
      "TENJO",
      "TIBACUY",
      "TIBIRITA",
      "TOCAIMA",
      "TOCANCIPÁ",
      "TOPAIPÍ",
      "UBALÁ",
      "UBAQUE",
      "UNE",
      "ÚTICA",
      "VENECIA",
      "VERGARA",
      "VIANÍ",
      "VILLA DE SAN DIEGO DE UBATÉ",
      "VILLAGÓMEZ",
      "VILLAPINZÓN",
      "VILLETA",
      "VIOTÁ",
      "YACOPÍ",
      "ZIPACÓN",
      "ZIPAQUIRÁ"
    ]
  },
  {
    "code": "94",
    "name": "Guainía",
    "municipalities": [
      "BARRANCOMINAS",
      "CACAHUAL",
      "INÍRIDA",
      "LA GUADALUPE",
      "MAPIRIPANA",
      "MORICHAL",
      "PANA PANA",
      "PUERTO COLOMBIA",
      "SAN FELIPE"
    ]
  },
  {
    "code": "95",
    "name": "Guaviare",
    "municipalities": [
      "CALAMAR",
      "EL RETORNO",
      "MIRAFLORES",
      "SAN JOSÉ DEL GUAVIARE"
    ]
  },
  {
    "code": "41",
    "name": "Huila",
    "municipalities": [
      "ACEVEDO",
      "AGRADO",
      "AIPE",
      "ALGECIRAS",
      "ALTAMIRA",
      "BARAYA",
      "CAMPOALEGRE",
      "COLOMBIA",
      "ELÍAS",
      "GARZÓN",
      "GIGANTE",
      "GUADALUPE",
      "HOBO",
      "ÍQUIRA",
      "ISNOS",
      "LA ARGENTINA",
      "LA PLATA",
      "NÁTAGA",
      "NEIVA",
      "OPORAPA",
      "PAICOL",
      "PALERMO",
      "PALESTINA",
      "PITAL",
      "PITALITO",
      "RIVERA",
      "SALADOBLANCO",
      "SAN AGUSTÍN",
      "SANTA MARÍA",
      "SUAZA",
      "TARQUI",
      "TELLO",
      "TERUEL",
      "TESALIA",
      "TIMANÁ",
      "VILLAVIEJA",
      "YAGUARÁ"
    ]
  },
  {
    "code": "44",
    "name": "La Guajira",
    "municipalities": [
      "ALBANIA",
      "BARRANCAS",
      "DIBULLA",
      "DISTRACCIÓN",
      "EL MOLINO",
      "FONSECA",
      "HATONUEVO",
      "LA JAGUA DEL PILAR",
      "MAICAO",
      "MANAURE",
      "RIOHACHA",
      "SAN JUAN DEL CESAR",
      "URIBIA",
      "URUMITA",
      "VILLANUEVA"
    ]
  },
  {
    "code": "47",
    "name": "Magdalena",
    "municipalities": [
      "ALGARROBO",
      "ARACATACA",
      "ARIGUANÍ",
      "CERRO DE SAN ANTONIO",
      "CHIVOLO",
      "CIÉNAGA",
      "CONCORDIA",
      "EL BANCO",
      "EL PIÑÓN",
      "EL RETÉN",
      "FUNDACIÓN",
      "GUAMAL",
      "NUEVA GRANADA",
      "PEDRAZA",
      "PIJIÑO DEL CARMEN",
      "PIVIJAY",
      "PLATO",
      "PUEBLOVIEJO",
      "REMOLINO",
      "SABANAS DE SAN ÁNGEL",
      "SALAMINA",
      "SAN SEBASTIÁN DE BUENAVISTA",
      "SAN ZENÓN",
      "SANTA ANA",
      "SANTA BÁRBARA DE PINTO",
      "SANTA MARTA",
      "SITIONUEVO",
      "TENERIFE",
      "ZAPAYÁN",
      "ZONA BANANERA"
    ]
  },
  {
    "code": "50",
    "name": "Meta",
    "municipalities": [
      "ACACÍAS",
      "BARRANCA DE UPÍA",
      "CABUYARO",
      "CASTILLA LA NUEVA",
      "CUBARRAL",
      "CUMARAL",
      "EL CALVARIO",
      "EL CASTILLO",
      "EL DORADO",
      "FUENTE DE ORO",
      "GRANADA",
      "GUAMAL",
      "LA MACARENA",
      "LEJANÍAS",
      "MAPIRIPÁN",
      "MESETAS",
      "PUERTO CONCORDIA",
      "PUERTO GAITÁN",
      "PUERTO LLERAS",
      "PUERTO LÓPEZ",
      "PUERTO RICO",
      "RESTREPO",
      "SAN CARLOS DE GUAROA",
      "SAN JUAN DE ARAMA",
      "SAN JUANITO",
      "SAN MARTÍN",
      "URIBE",
      "VILLAVICENCIO",
      "VISTAHERMOSA"
    ]
  },
  {
    "code": "52",
    "name": "Nariño",
    "municipalities": [
      "ALBÁN",
      "ALDANA",
      "ANCUYA",
      "ARBOLEDA",
      "BARBACOAS",
      "BELÉN",
      "BUESACO",
      "CHACHAGÜÍ",
      "COLÓN",
      "CONSACÁ",
      "CONTADERO",
      "CÓRDOBA",
      "CUASPUD CARLOSAMA",
      "CUMBAL",
      "CUMBITARA",
      "EL CHARCO",
      "EL PEÑOL",
      "EL ROSARIO",
      "EL TABLÓN DE GÓMEZ",
      "EL TAMBO",
      "FRANCISCO PIZARRO",
      "FUNES",
      "GUACHUCAL",
      "GUAITARILLA",
      "GUALMATÁN",
      "ILES",
      "IMUÉS",
      "IPIALES",
      "LA CRUZ",
      "LA FLORIDA",
      "LA LLANADA",
      "LA TOLA",
      "LA UNIÓN",
      "LEIVA",
      "LINARES",
      "LOS ANDES",
      "MAGÜÍ",
      "MALLAMA",
      "MOSQUERA",
      "NARIÑO",
      "OLAYA HERRERA",
      "OSPINA",
      "PASTO",
      "POLICARPA",
      "POTOSÍ",
      "PROVIDENCIA",
      "PUERRES",
      "PUPIALES",
      "RICAURTE",
      "ROBERTO PAYÁN",
      "SAMANIEGO",
      "SAN ANDRÉS DE TUMACO",
      "SAN BERNARDO",
      "SAN LORENZO",
      "SAN PABLO",
      "SAN PEDRO DE CARTAGO",
      "SANDONÁ",
      "SANTA BÁRBARA",
      "SANTACRUZ",
      "SAPUYES",
      "TAMINANGO",
      "TANGUA",
      "TÚQUERRES",
      "YACUANQUER"
    ]
  },
  {
    "code": "54",
    "name": "Norte de Santander",
    "municipalities": [
      "ÁBREGO",
      "ARBOLEDAS",
      "BOCHALEMA",
      "BUCARASICA",
      "CÁCHIRA",
      "CÁCOTA",
      "CHINÁCOTA",
      "CHITAGÁ",
      "CONVENCIÓN",
      "Cúcuta",
      "CUCUTILLA",
      "DURANIA",
      "EL CARMEN",
      "EL TARRA",
      "EL ZULIA",
      "GRAMALOTE",
      "HACARÍ",
      "HERRÁN",
      "LA ESPERANZA",
      "LA PLAYA",
      "LABATECA",
      "LOS PATIOS",
      "LOURDES",
      "MUTISCUA",
      "OCAÑA",
      "PAMPLONA",
      "PAMPLONITA",
      "PUERTO SANTANDER",
      "RAGONVALIA",
      "SALAZAR",
      "SAN CALIXTO",
      "SAN CAYETANO",
      "SANTIAGO",
      "SARDINATA",
      "SILOS",
      "TEORAMA",
      "TIBÚ",
      "TOLEDO",
      "VILLA CARO",
      "VILLA DEL ROSARIO"
    ]
  },
  {
    "code": "86",
    "name": "Putumayo",
    "municipalities": [
      "COLÓN",
      "MOCOA",
      "ORITO",
      "PUERTO ASÍS",
      "PUERTO CAICEDO",
      "PUERTO GUZMÁN",
      "PUERTO LEGUÍZAMO",
      "SAN FRANCISCO",
      "SAN MIGUEL",
      "SANTIAGO",
      "SIBUNDOY",
      "VALLE DEL GUAMUEZ",
      "VILLAGARZÓN"
    ]
  },
  {
    "code": "63",
    "name": "Quindío",
    "municipalities": [
      "ARMENIA",
      "BUENAVISTA",
      "CALARCÁ",
      "CIRCASIA",
      "CÓRDOBA",
      "FILANDIA",
      "GÉNOVA",
      "LA TEBAIDA",
      "MONTENEGRO",
      "PIJAO",
      "QUIMBAYA",
      "SALENTO"
    ]
  },
  {
    "code": "66",
    "name": "Risaralda",
    "municipalities": [
      "APÍA",
      "BALBOA",
      "BELÉN DE UMBRÍA",
      "DOSQUEBRADAS",
      "GUÁTICA",
      "LA CELIA",
      "LA VIRGINIA",
      "MARSELLA",
      "MISTRATÓ",
      "PEREIRA",
      "PUEBLO RICO",
      "QUINCHÍA",
      "SANTA ROSA DE CABAL",
      "SANTUARIO"
    ]
  },
  {
    "code": "68",
    "name": "Santander",
    "municipalities": [
      "AGUADA",
      "ALBANIA",
      "ARATOCA",
      "BARBOSA",
      "BARICHARA",
      "BARRANCABERMEJA",
      "BETULIA",
      "BOLÍVAR",
      "BUCARAMANGA",
      "CABRERA",
      "CALIFORNIA",
      "CAPITANEJO",
      "CARCASÍ",
      "CEPITÁ",
      "CERRITO",
      "CHARALÁ",
      "CHARTA",
      "CHIMA",
      "CHIPATÁ",
      "CIMITARRA",
      "CONCEPCIÓN",
      "CONFINES",
      "CONTRATACIÓN",
      "COROMORO",
      "CURITÍ",
      "EL CARMEN DE CHUCURI",
      "EL GUACAMAYO",
      "EL PEÑÓN",
      "EL PLAYÓN",
      "ENCINO",
      "ENCISO",
      "FLORIÁN",
      "FLORIDABLANCA",
      "GALÁN",
      "GÁMBITA",
      "GIRÓN",
      "GUACA",
      "GUADALUPE",
      "GUAPOTÁ",
      "GUAVATÁ",
      "GÜEPSA",
      "HATO",
      "JESÚS MARÍA",
      "JORDÁN",
      "LA BELLEZA",
      "LA PAZ",
      "LANDÁZURI",
      "LEBRIJA",
      "LOS SANTOS",
      "MACARAVITA",
      "MÁLAGA",
      "MATANZA",
      "MOGOTES",
      "MOLAGAVITA",
      "OCAMONTE",
      "OIBA",
      "ONZAGA",
      "PALMAR",
      "PALMAS DEL SOCORRO",
      "PÁRAMO",
      "PIEDECUESTA",
      "PINCHOTE",
      "PUENTE NACIONAL",
      "PUERTO PARRA",
      "PUERTO WILCHES",
      "RIONEGRO",
      "SABANA DE TORRES",
      "SAN ANDRÉS",
      "SAN BENITO",
      "SAN GIL",
      "SAN JOAQUÍN",
      "SAN JOSÉ DE MIRANDA",
      "SAN MIGUEL",
      "SAN VICENTE DE CHUCURÍ",
      "SANTA BÁRBARA",
      "SANTA HELENA DEL OPÓN",
      "SIMACOTA",
      "SOCORRO",
      "SUAITA",
      "SUCRE",
      "SURATÁ",
      "TONA",
      "VALLE DE SAN JOSÉ",
      "VÉLEZ",
      "VETAS",
      "VILLANUEVA",
      "ZAPATOCA"
    ]
  },
  {
    "code": "70",
    "name": "Sucre",
    "municipalities": [
      "BUENAVISTA",
      "CAIMITO",
      "CHALÁN",
      "COLOSÓ",
      "COROZAL",
      "COVEÑAS",
      "EL ROBLE",
      "GALERAS",
      "GUARANDA",
      "LA UNIÓN",
      "LOS PALMITOS",
      "MAJAGUAL",
      "MORROA",
      "OVEJAS",
      "PALMITO",
      "SAMPUÉS",
      "SAN BENITO ABAD",
      "SAN JOSÉ DE TOLUVIEJO",
      "SAN JUAN DE BETULIA",
      "SAN LUIS DE SINCÉ",
      "SAN MARCOS",
      "SAN ONOFRE",
      "SAN PEDRO",
      "SANTIAGO DE TOLÚ",
      "SINCELEJO",
      "SUCRE"
    ]
  },
  {
    "code": "73",
    "name": "Tolima",
    "municipalities": [
      "ALPUJARRA",
      "ALVARADO",
      "AMBALEMA",
      "ANZOÁTEGUI",
      "ARMERO",
      "ATACO",
      "CAJAMARCA",
      "CARMEN DE APICALÁ",
      "CASABIANCA",
      "CHAPARRAL",
      "COELLO",
      "COYAIMA",
      "CUNDAY",
      "DOLORES",
      "ESPINAL",
      "FALAN",
      "FLANDES",
      "FRESNO",
      "GUAMO",
      "HERVEO",
      "HONDA",
      "IBAGUÉ",
      "ICONONZO",
      "LÉRIDA",
      "LÍBANO",
      "MELGAR",
      "MURILLO",
      "NATAGAIMA",
      "ORTEGA",
      "PALOCABILDO",
      "PIEDRAS",
      "PLANADAS",
      "PRADO",
      "PURIFICACIÓN",
      "RIOBLANCO",
      "RONCESVALLES",
      "ROVIRA",
      "SALDAÑA",
      "SAN ANTONIO",
      "SAN LUIS",
      "SAN SEBASTIÁN DE MARIQUITA",
      "SANTA ISABEL",
      "SUÁREZ",
      "VALLE DE SAN JUAN",
      "VENADILLO",
      "VILLAHERMOSA",
      "VILLARRICA"
    ]
  },
  {
    "code": "76",
    "name": "Valle del Cauca",
    "municipalities": [
      "ALCALÁ",
      "ANDALUCÍA",
      "ANSERMANUEVO",
      "ARGELIA",
      "BOLÍVAR",
      "BUENAVENTURA",
      "BUGALAGRANDE",
      "CAICEDONIA",
      "CALI",
      "CALIMA",
      "CANDELARIA",
      "CARTAGO",
      "DAGUA",
      "EL ÁGUILA",
      "EL CAIRO",
      "EL CERRITO",
      "EL DOVIO",
      "FLORIDA",
      "GINEBRA",
      "GUACARÍ",
      "GUADALAJARA DE BUGA",
      "JAMUNDÍ",
      "LA CUMBRE",
      "LA UNIÓN",
      "LA VICTORIA",
      "OBANDO",
      "PALMIRA",
      "PRADERA",
      "RESTREPO",
      "RIOFRÍO",
      "ROLDANILLO",
      "SAN PEDRO",
      "SEVILLA",
      "TORO",
      "TRUJILLO",
      "TULUÁ",
      "ULLOA",
      "VERSALLES",
      "VIJES",
      "YOTOCO",
      "YUMBO",
      "ZARZAL"
    ]
  },
  {
    "code": "97",
    "name": "Vaupés",
    "municipalities": [
      "CARURÚ",
      "MITÚ",
      "PACOA",
      "PAPUNAHUA",
      "TARAIRA",
      "YAVARATÉ"
    ]
  },
  {
    "code": "99",
    "name": "Vichada",
    "municipalities": [
      "CUMARIBO",
      "LA PRIMAVERA",
      "PUERTO CARREÑO",
      "SANTA ROSALÍA"
    ]
  }
]

export const departmentOptions = colombiaDepartments.map(({ code, name }) => ({ value: code, label: name }))

function titleCase(value: string) {
  return value.toLocaleLowerCase('es-CO').replace(/(^|[\s-])([a-záéíóúüñ])/giu, (_, separator: string, letter: string) => `${separator}${letter.toLocaleUpperCase('es-CO')}`)
}

export function municipalitiesForDepartment(departmentCode: string) {
  return (colombiaDepartments.find((department) => department.code === departmentCode)?.municipalities || []).map(titleCase)
}

export function departmentName(departmentCode: string) {
  return colombiaDepartments.find((department) => department.code === departmentCode)?.name || ''
}

export function findDepartmentForMunicipality(municipality: string) {
  const normalized = municipality.trim().toLocaleLowerCase('es-CO')
  return colombiaDepartments.find((department) => department.municipalities.some((item) => item.toLocaleLowerCase('es-CO') === normalized))
}
